  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: dev
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: bunyaminaltinok/pyt:v$DOCKER_BUILD_NUMBER
        ports:
        - containerPort: 5002