apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: dev
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30030
    protocol: TCP