apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: prod
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30052
    protocol: TCP